apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-stage
  namespace: argocd
spec: 
  project: default
  source:
     repoURL: https://github.com/amosegonmwan/aws-eks-argocd.git
     targetRevision: main
     path: stage
  destination:
    server: https://kubernetes.default.svc
    namespace: stage

  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true