apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: appset
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - app: my-dev
            path: dev
            revision: main 
            namespace: dev
            repo: aws-eks-argocd

          - app: my-prod
            path: prod
            revision: main 
            namespace: prod
            repo: aws-eks-argocd 

          - app: my-stage
            path: stage
            revision: main 
            namespace: stage
            repo: aws-eks-argocd 

          - app: my-monitoring
            path: prod
            revision: main 
            namespace: monitoring
            repo: argocd-demo-1 

  template:
    metadata:
      name: '{{app}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/amosegonmwan/{{repo}}.git
        targetRevision: '{{revision}}'
        path: '{{path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{namespace}}'
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
        automated:
          selfHeal: true
          prune: true
          
