apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp2-deployment
spec:
  replicas: 6
  selector:
    matchLabels:
      app: myapp2
  template:
    metadata:
      name: myapp2-pod
      labels:
        app: myapp2
    spec:
      containers:
        - name: myapp2-container
          image: nginx
          ports:
            - containerPort: 80
