apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp3-deployment
spec:
  selector:
    matchLabels:
     app: myapp3
  replicas: 8
  template:
    metadata:
      name: myapp3-prod
      labels:
        app: myapp3
    spec:
       containers:
       - name: myapp3-container
         image: nginx
         ports:
         - containerPort: 80
