apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp4-deployment
spec:
  selector:
    matchLabels:
     app: myapp4
  replicas: 8
  template:
    metadata:
      name: myapp4-prod
      labels:
        app: myapp4
    spec:
       containers:
       - name: myapp4-container
         image: nginx
         ports:
         - containerPort: 80
